//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID04_MaterialDetail
    {
        public int BIDMatDtlID { get; set; }
        public int BIDMatHeaderID { get; set; }
        public string PartNum { get; set; }
        public string PartNumDesc { get; set; }
        public decimal Qty { get; set; }
        public string UOM { get; set; }
        public decimal Cost { get; set; }
        public Nullable<byte> ImportFlag { get; set; }
    
        public virtual BID03_MaterialHeader BID03_MaterialHeader { get; set; }
    }
}
