//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public partial class BID07_Concrete
    {
        public string RowNum { get; set; }
        public int CONCID { get; set; }
        public int BIDID { get; set; }
        public string PstTypId { get; set; }
        public string ConcreteType { get; set; }
        public int HoleQty { get; set; }
        public int HoleDia { get; set; }
        public int HoleDepth { get; set; }
        public Nullable<decimal> CalcYds { get; set; }
        public decimal RoundFactor { get; set; }
        public Nullable<decimal> BidYds { get; set; }
        public decimal CostPerYd { get; set; }
        public Nullable<decimal> ExtConcCost { get; set; }
    
        public virtual BID01_Headers BID01_Headers { get; set; }

        public SelectList PostTypeDdlForUI { get; set; }
        public SelectList ConcreteTypeDdlForUI { get; set; }
        public SelectList RoundFactorDdlForUI { get; set; }
    }
}
