//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID13_PFQMaterial
    {
        public int PFQMatID { get; set; }
        public int PFQHeaderID { get; set; }
        public string PartNum { get; set; }
        public decimal Qty { get; set; }
        public decimal Cost { get; set; }
    
        public virtual BID12_PFQHeader BID12_PFQHeader { get; set; }
    }
}
