//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID16_PFQCrewProfile
    {
        public int PFQDefineCrewID { get; set; }
        public int BIDID { get; set; }
        public int CrewPositionID { get; set; }
        public int HeadCount { get; set; }
        public decimal OnSiteRate { get; set; }
        public decimal OffsiteRate { get; set; }
        public decimal BenefitRate { get; set; }
        public decimal RetirementBenefitRate { get; set; }
        public decimal PayrollTaxRate { get; set; }
        public decimal WorkCompRate { get; set; }
        public decimal OnSiteMhs { get; set; }
        public decimal LoadMhs { get; set; }
        public decimal DriveMhs { get; set; }
        public int FormLocation { get; set; }
    
        public virtual BID01_Headers BID01_Headers { get; set; }
        public virtual Setup03_DefaultCrewSize Setup03_DefaultCrewSize { get; set; }
    }
}
