//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID18_PFQOtherCosts
    {
        public int PQFOtherCostID { get; set; }
        public int PFQHeaderID { get; set; }
        public int PFQOtherCostTypeID { get; set; }
        public decimal Qty { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> OtherCostExt { get; set; }
        public decimal Markup { get; set; }
        public Nullable<decimal> OtherCostMarkup { get; set; }
        public Nullable<decimal> OtherCostTotals { get; set; }
    
        public virtual BID12_PFQHeader BID12_PFQHeader { get; set; }
        public virtual Setup11_OtherCostTypes Setup11_OtherCostTypes { get; set; }
    }
}
