//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM01_Headers
    {
        public BOM01_Headers()
        {
            this.BOM02_MaterialBills = new HashSet<BOM02_MaterialBills>();
            this.BOM03_LaborRoutings = new HashSet<BOM03_LaborRoutings>();
        }
    
        public string BomPartNum { get; set; }
        public Nullable<System.DateTime> LastDateRevised { get; set; }
    
        public virtual INV01_Master INV01_Master { get; set; }
        public virtual ICollection<BOM02_MaterialBills> BOM02_MaterialBills { get; set; }
        public virtual ICollection<BOM03_LaborRoutings> BOM03_LaborRoutings { get; set; }
    }
}
