//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUI02_LaborFormParams
    {
        public int FormParamId { get; set; }
        public int FieldLbrTypeID { get; set; }
        public string ElemLabelText { get; set; }
        public string ElemBaseName { get; set; }
        public int NumberOfElem { get; set; }
        public int Sort { get; set; }
        public bool SpaceAfter { get; set; }
    
        public virtual Setup23_FieldLaborTypes Setup23_FieldLaborTypes { get; set; }
    }
}
