//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV02_ProdLines
    {
        public INV02_ProdLines()
        {
            this.INV03_CatalogLayout = new HashSet<INV03_CatalogLayout>();
        }
    
        public string ProdLineID { get; set; }
        public string ProdLine { get; set; }
        public string ProdLineSort { get; set; }
        public byte InCatalogProdLine { get; set; }
    
        public virtual ICollection<INV03_CatalogLayout> INV03_CatalogLayout { get; set; }
    }
}
