//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV01_Master
    {
        public INV01_Master()
        {
            this.BOM02_MaterialBills = new HashSet<BOM02_MaterialBills>();
            this.INV10_MasVendorPricing = new HashSet<INV10_MasVendorPricing>();
            this.INV11_VendorPartNumCrossRef = new HashSet<INV11_VendorPartNumCrossRef>();
            this.PFP02_Material = new HashSet<PFP02_Material>();
        }
    
        public string PartNum { get; set; }
        public string PartDescription { get; set; }
        public string SubClassID { get; set; }
        public string StdUM { get; set; }
        public string PurchaseUM { get; set; }
        public string SalesUM { get; set; }
        public string Size { get; set; }
        public decimal Dimention1 { get; set; }
        public string Dimention1Uom { get; set; }
        public decimal Dimention2 { get; set; }
        public string Dimention2Uom { get; set; }
        public decimal Dimention3 { get; set; }
        public string Dimention3Uom { get; set; }
        public decimal Weight { get; set; }
        public string WeightUom { get; set; }
        public string ProcurementTypeID { get; set; }
        public string ExtendedDescription { get; set; }
        public decimal StdCost { get; set; }
        public Nullable<decimal> StdCostFuture { get; set; }
        public Nullable<decimal> StdCostPrevious { get; set; }
        public Nullable<System.DateTime> DateOfPriceChange { get; set; }
        public Nullable<System.DateTime> DateOfPriceChangeFuture { get; set; }
        public Nullable<byte> Discontinued { get; set; }
        public Nullable<byte> CountSheet { get; set; }
        public int RdmCount { get; set; }
        public Nullable<int> ExtendedDescriptionKey { get; set; }
        public Nullable<byte> ExcludeFrmCatalogPart { get; set; }
        public Nullable<byte> IncludeOnWebsite { get; set; }
        public decimal MpfId { get; set; }
        public int ColorId { get; set; }
        public string Web_Part_Description { get; set; }
    
        public virtual BOM01_Headers BOM01_Headers { get; set; }
        public virtual ICollection<BOM02_MaterialBills> BOM02_MaterialBills { get; set; }
        public virtual INV05_SubClass INV05_SubClass { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure1 { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure2 { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure3 { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure4 { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure5 { get; set; }
        public virtual INV07_UnitOfMeasure INV07_UnitOfMeasure6 { get; set; }
        public virtual INV09_MasterPricingFamilies INV09_MasterPricingFamilies { get; set; }
        public virtual INV18_Color INV18_Color { get; set; }
        public virtual ICollection<INV10_MasVendorPricing> INV10_MasVendorPricing { get; set; }
        public virtual ICollection<INV11_VendorPartNumCrossRef> INV11_VendorPartNumCrossRef { get; set; }
        public virtual ICollection<PFP02_Material> PFP02_Material { get; set; }
    }
}
