//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV07_UnitOfMeasure
    {
        public INV07_UnitOfMeasure()
        {
            this.INV01_Master = new HashSet<INV01_Master>();
            this.INV01_Master1 = new HashSet<INV01_Master>();
            this.INV01_Master2 = new HashSet<INV01_Master>();
            this.INV01_Master3 = new HashSet<INV01_Master>();
            this.INV01_Master4 = new HashSet<INV01_Master>();
            this.INV01_Master5 = new HashSet<INV01_Master>();
            this.INV01_Master6 = new HashSet<INV01_Master>();
        }
    
        public string UnitOfMeasure { get; set; }
        public string UomDescription { get; set; }
    
        public virtual ICollection<INV01_Master> INV01_Master { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master1 { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master2 { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master3 { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master4 { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master5 { get; set; }
        public virtual ICollection<INV01_Master> INV01_Master6 { get; set; }
    }
}
