//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV05_SubClass
    {
        public INV05_SubClass()
        {
            this.INV01_Master = new HashSet<INV01_Master>();
            this.INV15_WebSiteDetails = new HashSet<INV15_WebSiteDetails>();
        }
    
        public string SubClassID { get; set; }
        public string SubClass { get; set; }
        public string ClassID { get; set; }
        public decimal CfsMargin { get; set; }
        public decimal CfsMarginFuture { get; set; }
        public decimal CfsMarginPrevious { get; set; }
        public decimal RetailMargin { get; set; }
        public decimal RetailMarginFuture { get; set; }
        public decimal RetailMarginPrevious { get; set; }
        public decimal Level2Margin { get; set; }
        public decimal Level2MarginFuture { get; set; }
        public decimal Level2MarginPrevious { get; set; }
        public decimal Level3Margin { get; set; }
        public decimal Level3MarginFuture { get; set; }
        public decimal Level3MarginPrevious { get; set; }
        public decimal Level4Margin { get; set; }
        public decimal Level4MarginFuture { get; set; }
        public decimal Level4MarginPrevious { get; set; }
        public decimal Level5Margin { get; set; }
        public decimal Level5MarginFuture { get; set; }
        public decimal Level5MarginPrevious { get; set; }
        public int RetailQty { get; set; }
        public int Level2Qty { get; set; }
        public int Level3Qty { get; set; }
        public int Level4Qty { get; set; }
        public System.DateTime DateOfMarginChange { get; set; }
        public Nullable<decimal> SubClassSort { get; set; }
        public string ImagePath { get; set; }
        public byte SubClassInCatalog { get; set; }
        public byte IncludeSubClassOnWebsite { get; set; }
        public Nullable<byte> IncludeSubClassInPFP { get; set; }
    
        public virtual ICollection<INV01_Master> INV01_Master { get; set; }
        public virtual INV04_Class INV04_Class { get; set; }
        public virtual ICollection<INV15_WebSiteDetails> INV15_WebSiteDetails { get; set; }
    }
}
