//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV10_MasVendorPricing
    {
        public int MasVendorPricingId { get; set; }
        public string Division { get; set; }
        public string VendorNumber { get; set; }
        public string ProductLine { get; set; }
        public string ItemNumber { get; set; }
        public string ExtendedItemNumber { get; set; }
        public string PricingMethod { get; set; }
        public decimal BreakQty1 { get; set; }
        public decimal BreakQty2 { get; set; }
        public decimal BreakQty3 { get; set; }
        public decimal BreakQty4 { get; set; }
        public decimal BreakQty5 { get; set; }
        public decimal BreakQty6 { get; set; }
        public decimal BreakQty7 { get; set; }
        public decimal BreakQty8 { get; set; }
        public decimal DiscountMarkup1 { get; set; }
        public decimal DiscountMarkup2 { get; set; }
        public decimal DiscountMarkup3 { get; set; }
        public decimal DiscountMarkup4 { get; set; }
        public decimal DiscountMarkup5 { get; set; }
        public decimal DiscountMarkup6 { get; set; }
        public decimal DiscountMarkup7 { get; set; }
        public decimal DiscountMarkup8 { get; set; }
        public string VendorPartNumber { get; set; }
        public string VendorUom { get; set; }
        public Nullable<double> VendorCost { get; set; }
        public Nullable<decimal> ConversionFactor { get; set; }
        public string InventoryUom { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual INV01_Master INV01_Master { get; set; }
    }
}
