//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFP11_ComponentType
    {
        public PFP11_ComponentType()
        {
            this.PFP01_Header = new HashSet<PFP01_Header>();
        }
    
        public int PFPComponentTypeId { get; set; }
        public string PFPComponentType { get; set; }
        public decimal Sort { get; set; }
    
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
    }
}
