//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PRJ04_JobSites
    {
        public PRJ04_JobSites()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
        [ScaffoldColumn(false)]
        public int JobSiteId { get; set; }
        [Display(Name ="Commercial Customer")]
        public bool IsCommercial { get; set; }

        [Display(Name = "Job Name")]
        [Required]
        public string JobName { get; set; }
        [Display(Name = "First Name")]
        [Required]
        public string BillingFirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        public string BillingLastName { get; set; }
        [Display(Name = "Company Name")]
        public string BillingCompanyName { get; set; }
        [Display(Name = "Job Site Address")]
        [Required]
        public string JobSiteAddress { get; set; }
        [Display(Name = "City")]
        [Required]
        public string JobSiteCity { get; set; }
        [Display(Name = "State")]
        [Required]
        public string JobSiteState { get; set; }
        [Display(Name = "Zip")]
        [Required]
        public string JobSiteZip { get; set; }
        [Display(Name = "Phone")]
        [Required]
        public string JobSitePhone { get; set; }
        [Display(Name = "Ext")]
        public string JobSitePhoneExt { get; set; }
        [Display(Name = "Fax")]
        public string JobSiteFax { get; set; }
        [Display(Name = "Mobile")]
        public string JobSiteMobilePhone { get; set; }
        [Display(Name = "Email")]
        public string JobSiteEMail { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> SalApptId { get; set; }

        public Nullable<int> SalContId { get; set; }

        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
        public virtual SAL03_ResAppointments SAL03_ResAppointments { get; set; }
    }
}
