//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PRJ08_BillingInfo
    {
        public PRJ08_BillingInfo()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
        [ScaffoldColumn(false)]
        public int PRJBillingID { get; set; }
        [Display(Name = "First Name")]
        [Required]
        public string BillingFirstName { get; set; }
        [Display(Name = "LastName")]
        [Required]
        public string BillingLastName { get; set; }
        [Display(Name = "Company Name")]
        public string BillingCompanyName { get; set; }
        [Display(Name = "Job Site Address")]
        [Required]
        public string BillingAddress { get; set; }
        [Display(Name = "City")]
        [Required]
        public string BillingCity { get; set; }
        [Display(Name = "State")]
        [Required]
        public string BillingState { get; set; }
        [Display(Name = "Zip")]
        [Required]
        public string BillingZip { get; set; }
        [Display(Name = "Country")]
        [Required]
        public string BillingCountry { get; set; }
        [Display(Name = "Phone")]
        [Required]
        public string BillingPhone { get; set; }
        [Display(Name = "Ext")]
        public string BillingPhoneExt { get; set; }
        [Display(Name = "Fax")]
        public string BillingFax { get; set; }
        [Display(Name = "Mobile")]
        public string BillingMobilePhone { get; set; }
        [Display(Name = "Email")]
        public string BillingEMail { get; set; }
    
        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
    }
}
