//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ02_ContractPg
    {
        public int ContractId { get; set; }
        public Nullable<int> ProjectHeaderId { get; set; }
        public string ContractName { get; set; }
        public Nullable<double> ContractAmount { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> BalanceDue { get; set; }
        public string ScopeOfJob { get; set; }
        public string SalesmanPhone { get; set; }
    }
}
