//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PRJ05_JobStatus
    {
        public PRJ05_JobStatus()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
        [ScaffoldColumn(false)]
        public string JobStatusId { get; set; }
        [Display(Name = "Division")]
        public string Company { get; set; }
        [Display(Name = "Rate Type")]
        [Required]
        public string RateType { get; set; }
        [Display(Name = "Drive Time")]
        public string DriveTime { get; set; }
        [Display(Name="Job Status")]
        [Required]
        public string JobStatusName { get; set; }
        [Display(Name = "Start Date")]
        public string StartDate { get; set; }
        public string CommId { get; set; }
        public string PRJ_ProjectName { get; set; }
        public string PRJ_DivId { get; set; }
        public int PRJ_DriveMultiplier { get; set; }
        public decimal PRJ_DriveTime1Way { get; set; }
        public decimal InstallCommRate { get; set; }
        public int JobSiteId { get; set; }
        public int BillingId { get; set; }
        public int? SalContId { get; set; }
        public string PRJ_Notes { get; set; }


        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
    }
}
