//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRL08_TimeEntryDetail
    {
        public int DetailId { get; set; }
        public int EntryId { get; set; }
        public int FieldLbrDtlsID { get; set; }
        public decimal QtyComplete { get; set; }
        public decimal ManHours { get; set; }
        public int ProductionCodeId { get; set; }
        public string Memo { get; set; }
    
        public virtual PRL07_TimeEntryHeader PRL07_TimeEntryHeader { get; set; }
        public virtual Setup00_ProductionCodes Setup00_ProductionCodes { get; set; }
        public virtual Setup24_FieldLaborDetails Setup24_FieldLaborDetails { get; set; }
    }
}
