//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRL07_TimeEntryHeader
    {
        public PRL07_TimeEntryHeader()
        {
            this.PRL08_TimeEntryDetail = new HashSet<PRL08_TimeEntryDetail>();
            this.PRL09_TimeEntryMhs = new HashSet<PRL09_TimeEntryMhs>();
        }
    
        public int EntryId { get; set; }
        public int BIDID { get; set; }
        public System.DateTime Date { get; set; }
        public int EarnCodeId { get; set; }
        public int DepartmentCodeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string UserName { get; set; }
    
        public virtual BID01_Headers BID01_Headers { get; set; }
        public virtual Setup00_EarningCodes Setup00_EarningCodes { get; set; }
        public virtual ICollection<PRL08_TimeEntryDetail> PRL08_TimeEntryDetail { get; set; }
        public virtual ICollection<PRL09_TimeEntryMhs> PRL09_TimeEntryMhs { get; set; }
    }
}
