//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SAL02_Contacts
    {
        public SAL02_Contacts()
        {
            this.SAL03_ResAppointments = new HashSet<SAL03_ResAppointments>();
        }
    
        public int SalContId { get; set; }

        [Display(Name ="First Name")]
        [Required(AllowEmptyStrings =false,ErrorMessage ="Please Enter First Name")]
        public string SalContFirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Last Name")]
        public string SalContLastName { get; set; }

        [Display(Name = "Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Address")]
        public string SalContAddress { get; set; }

        [Display(Name = "City")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter City")]
        public string SalContCity { get; set; }

        [Display(Name = "State")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter State")]
        public string SalContState { get; set; }

        [Display(Name = "Zip Code")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Zip Code")]
        public string SalContZip { get; set; }

        [Display(Name = "Phone")]
        public string SalContPhone { get; set; }

        [Display(Name = "Ext")]
        public string SalContPhoneExt { get; set; }

        [Display(Name = "Fax Number")]
        public string SalContFax { get; set; }

        [Display(Name = "Mobile Phone")]
        public string SalContMobile { get; set; }

        [Display(Name = "Email Exists?")]
        public bool EmailExists { get; set; }

        [Display(Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Email ID")]
        public string SalContEmail { get; set; }

        [ScaffoldColumn(false)]
        public string SalCompId { get; set; }

        [Display(Name = "Active")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Select Active Status")]
        public string SalContActiveFlag { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<int> LedSourceId { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<DateTime> SalContDateCreated { get; set; }

        public virtual PRJ06_LedSource PRJ06_LedSource { get; set; }
        public virtual SAL01_Company SAL01_Company { get; set; }
        public virtual ICollection<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
    }
}
