//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SAL01_Company
    {
        public SAL01_Company()
        {
            this.SAL02_Contacts = new HashSet<SAL02_Contacts>();
        }
    
       
        public string SalCompId { get; set; }

        [Display(Name ="Company Name")]
        [Required(AllowEmptyStrings =false, ErrorMessage = "Please Enter Company Name")]
        public string SalCompName { get; set; }

        [Display(Name = "Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Address")]
        public string SalCompAddress { get; set; }

        [Display(Name = "City")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter City")]
        public string SalCompCity { get; set; }

        [Display(Name = "State")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter State")]
        public string SalCompState { get; set; }

        [Display(Name = "Zip Code")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Zip Code")]
        public string SalCompZip { get; set; }

        [Display(Name = "Phone")]
        public string SalCompPhone { get; set; }

        [Display(Name = "Ext")]
        public string SalCompPhoneExt { get; set; }

        [Display(Name = "Fax Number")]
        public string SalCompFax { get; set; }

        [Display(Name = "Mobile Phone")]
        public string SalCompMobile { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name ="Email Exists")]
        public bool EmailExists { get; set; }

        [Display(Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Enter Email ID")]
        public string SalCompEMail { get; set; }

       [ScaffoldColumn(false)]
        public System.DateTime SalCompDateCreated { get; set; }

        [Display(Name = "Active")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Select Active status")]
        public Nullable<bool> SalCompActiveFlag { get; set; }

        public virtual ICollection<SAL02_Contacts> SAL02_Contacts { get; set; }
    }
}
