//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup11_OtherCostTypes
    {
        public Setup11_OtherCostTypes()
        {
            this.BID08_OtherCosts = new HashSet<BID08_OtherCosts>();
            this.BID18_PFQOtherCosts = new HashSet<BID18_PFQOtherCosts>();
        }
    
        public string OtherCostTypeID { get; set; }
        public string OtherCostType { get; set; }
        public decimal DefaultMarkup { get; set; }
    
        public virtual ICollection<BID08_OtherCosts> BID08_OtherCosts { get; set; }
        public virtual ICollection<BID18_PFQOtherCosts> BID18_PFQOtherCosts { get; set; }
    }
}
