//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup30_DigTypes
    {
        public Setup30_DigTypes()
        {
            this.BID01_Headers = new HashSet<BID01_Headers>();
            this.PFP01_Header = new HashSet<PFP01_Header>();
        }
    
        public int DigTypeID { get; set; }
        public string DigType { get; set; }
        public decimal PercentOfDigStandard { get; set; }
    
        public virtual ICollection<BID01_Headers> BID01_Headers { get; set; }
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
    }
}
