//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup02_MhRates
    {
        public Setup02_MhRates()
        {
            this.PFP01_Header = new HashSet<PFP01_Header>();
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
            this.Setup03_DefaultCrewSize = new HashSet<Setup03_DefaultCrewSize>();
        }
    
        public string MhRateID { get; set; }
        public string MhRate { get; set; }
        public string DivID { get; set; }
        public int ConstructionTypeId { get; set; }
        public decimal OnSiteMhs { get; set; }
        public decimal DefaultDrive1Way { get; set; }
        public decimal DriveMultipler { get; set; }
        public Nullable<decimal> DriveMhs { get; set; }
        public decimal LoadMhs { get; set; }
        public Nullable<decimal> OffsiteMhs { get; set; }
        public Nullable<decimal> TotalMhs { get; set; }
        public byte Rate_True_False { get; set; }
    
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
        public virtual Setup01_ConstructionType Setup01_ConstructionType { get; set; }
        public virtual Setup01_Divisions Setup01_Divisions { get; set; }
        public virtual ICollection<Setup03_DefaultCrewSize> Setup03_DefaultCrewSize { get; set; }
    }
}
