//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetUp00_PayrollTaxes
    {
        public int PayrollTaxId { get; set; }
        public string PayRollTaxType { get; set; }
        public decimal TaxRate { get; set; }
        public byte CalcRegPay { get; set; }
        public byte CalcOtPay { get; set; }
        public byte CalcCommPay { get; set; }
        public byte CalcBenniPay { get; set; }
        public decimal CapAmount { get; set; }
    }
}
