//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup03_DefaultCrewSize
    {
        public Setup03_DefaultCrewSize()
        {
            this.BID16_PFQCrewProfile = new HashSet<BID16_PFQCrewProfile>();
        }
    
        public string CrewPositionID { get; set; }
        public string CrewPosition { get; set; }
        public int HeadCount { get; set; }
        public decimal OnSiteRate { get; set; }
        public decimal OffsiteRate { get; set; }
        public decimal BenefitRate { get; set; }
        public decimal RetirementBenefitRate { get; set; }
        public int WorkCompID { get; set; }
        public string MhRateID { get; set; }
        public decimal SubOnSiteRate { get; set; }
        public decimal SubOffSiteRate { get; set; }
    
        public virtual ICollection<BID16_PFQCrewProfile> BID16_PFQCrewProfile { get; set; }
        public virtual Setup00_WorkCompRates Setup00_WorkCompRates { get; set; }
        public virtual Setup02_MhRates Setup02_MhRates { get; set; }
    }
}
