//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup01_ConstructionType
    {
        public Setup01_ConstructionType()
        {
            this.Setup02_MhRates = new HashSet<Setup02_MhRates>();
            this.Setup25_FenceTypes = new HashSet<Setup25_FenceTypes>();
        }
    
        public int ConstructionTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Setup02_MhRates> Setup02_MhRates { get; set; }
        public virtual ICollection<Setup25_FenceTypes> Setup25_FenceTypes { get; set; }
    }
}
