//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup25_FenceTypes
    {
        public Setup25_FenceTypes()
        {
            this.BID01_Headers = new HashSet<BID01_Headers>();
            this.PFP01_Header = new HashSet<PFP01_Header>();
            this.SAL03_ResAppointments = new HashSet<SAL03_ResAppointments>();
            this.Setup04_DefaultCrewEquipment = new HashSet<Setup04_DefaultCrewEquipment>();
        }
    
        public int FenceTypeID { get; set; }
        public string FenceType { get; set; }
        public string DivID { get; set; }
        public Nullable<int> ConstructionTypeId { get; set; }
        public Nullable<int> FenceFamilyId { get; set; }
        public decimal SupervisonMarkup { get; set; }
        public decimal MaterialMarkUp { get; set; }
        public decimal LaborMarkUp { get; set; }
        public decimal JobMarkUp { get; set; }
        public decimal PFPJobMarkup { get; set; }
        public Nullable<decimal> Sort { get; set; }
        public Nullable<int> CrossRefOldFenceTypID { get; set; }
    
        public virtual ICollection<BID01_Headers> BID01_Headers { get; set; }
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
        public virtual ICollection<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
        public virtual Setup01_ConstructionType Setup01_ConstructionType { get; set; }
        public virtual Setup01_Divisions Setup01_Divisions { get; set; }
        public virtual ICollection<Setup04_DefaultCrewEquipment> Setup04_DefaultCrewEquipment { get; set; }
        public virtual Setup25_FenceFamily Setup25_FenceFamily { get; set; }
    }
}
