//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup00_EarningCodes
    {
        public Setup00_EarningCodes()
        {
            this.PRL07_TimeEntryHeader = new HashSet<PRL07_TimeEntryHeader>();
        }
    
        public int EarnCodeID { get; set; }
        public string EarnCode { get; set; }
        public string DivID { get; set; }
        public int Sort { get; set; }
        public byte EligibleForOT { get; set; }
    
        public virtual ICollection<PRL07_TimeEntryHeader> PRL07_TimeEntryHeader { get; set; }
        public virtual Setup01_Divisions Setup01_Divisions { get; set; }
    }
}
