//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup24_FieldLaborDetails
    {
        public Setup24_FieldLaborDetails()
        {
            this.BID02_LaborItems = new HashSet<BID02_LaborItems>();
            this.BID14_PFQLabor = new HashSet<BID14_PFQLabor>();
            this.PFP03_Labor = new HashSet<PFP03_Labor>();
            this.PRL08_TimeEntryDetail = new HashSet<PRL08_TimeEntryDetail>();
        }
    
        public int FieldLbrDtlsID { get; set; }
        public string FieldLbrDesc { get; set; }
        public string FieldLbrUom { get; set; }
        public decimal FieldLbrMhs { get; set; }
        public int FieldLbrTypeID { get; set; }
        public byte PrintToTimeSheet { get; set; }
        public string Sort { get; set; }
    
        public virtual ICollection<BID02_LaborItems> BID02_LaborItems { get; set; }
        public virtual ICollection<BID14_PFQLabor> BID14_PFQLabor { get; set; }
        public virtual ICollection<PFP03_Labor> PFP03_Labor { get; set; }
        public virtual ICollection<PRL08_TimeEntryDetail> PRL08_TimeEntryDetail { get; set; }
        public virtual Setup23_FieldLaborTypes Setup23_FieldLaborTypes { get; set; }
    }
}
