//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup31_ShopLocations
    {
        public Setup31_ShopLocations()
        {
            this.Setup32_ShopLabors = new HashSet<Setup32_ShopLabors>();
        }
    
        public int ShopLocID { get; set; }
        public string ShopName { get; set; }
        public decimal ShopRate { get; set; }
        public decimal ShopRateFuture { get; set; }
        public decimal ShopRatePrevious { get; set; }
        public decimal ShopBurdenPct { get; set; }
        public decimal ShopBurdenPctFuture { get; set; }
        public decimal ShopBurdenPctPrevious { get; set; }
        public string AccountKey_DirectLbr { get; set; }
        public string AccountKey_BurdenManufact { get; set; }
    
        public virtual ICollection<Setup32_ShopLabors> Setup32_ShopLabors { get; set; }
    }
}
