//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup28_FencePostTypes
    {
        public string PstTypID { get; set; }
        public string PostType { get; set; }
    }

    public partial class vFilterEstConcrete
    {
        public string PartNum  { get; set; }
        public string PartDescription { get; set; }
    }
}
