//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBIDCrewTimeSheetOnsite
    {
        public int BIDID { get; set; }
        public int FieldLbrDtlsID { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> MhsEa { get; set; }
        public Nullable<decimal> PayEa { get; set; }
        public Nullable<decimal> MhsTotal { get; set; }
        public Nullable<decimal> PayTotal { get; set; }
    }
}
