//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBIDMaterialCost
    {
        public int BIDID { get; set; }
        public Nullable<decimal> CfsCost { get; set; }
        public Nullable<byte> OverRideCost { get; set; }
        public Nullable<decimal> OverRiddenCost { get; set; }
    }
}
