//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBOMCombinedDetail
    {
        public string PartNum { get; set; }
        public string CompId { get; set; }
        public string ShopLbrDesc { get; set; }
        public decimal Qty { get; set; }
        public string Uom { get; set; }
        public string Type { get; set; }
    }
}
