//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBOMReport
    {
        public string PartNum { get; set; }
        public string PartDescription { get; set; }
        public string CompId { get; set; }
        public string ShopLbrDesc { get; set; }
        public decimal Qty { get; set; }
        public string Uom { get; set; }
        public string Type { get; set; }
        public string ProdLine { get; set; }
        public string SubClassID { get; set; }
        public decimal Dimention1 { get; set; }
        public string Dimention1Uom { get; set; }
        public decimal Dimention2 { get; set; }
        public string Dimention2Uom { get; set; }
        public decimal Dimention3 { get; set; }
        public string Dimention3Uom { get; set; }
    }
}
