//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCatalogPricing
    {
        public string PartNum { get; set; }
        public string PartDescription { get; set; }
        public string StdUM { get; set; }
        public decimal StdCost { get; set; }
        public Nullable<decimal> CfsCost { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> Level2Price { get; set; }
        public Nullable<decimal> Level3Price { get; set; }
        public Nullable<decimal> Level4Price { get; set; }
        public Nullable<decimal> Level5Price { get; set; }
        public string ImagePath { get; set; }
        public int RetailQty { get; set; }
        public int Level2Qty { get; set; }
        public int Level3Qty { get; set; }
    }
}
