//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGeoDrawPricingPanel
    {
        public string StylePricingNumber { get; set; }
        public Nullable<decimal> PanelPrice { get; set; }
        public Nullable<decimal> PanelMatCost { get; set; }
        public int PFPComponentTypeId { get; set; }
    }
}
