//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPFPCrewRate
    {
        public string MhRateID { get; set; }
        public Nullable<decimal> OnSiteRate { get; set; }
        public Nullable<decimal> OffsiteRate { get; set; }
        public Nullable<decimal> BenefitRate { get; set; }
        public Nullable<decimal> RetirementBenefitRate { get; set; }
        public Nullable<decimal> PayrollTaxRate { get; set; }
        public Nullable<decimal> WorkCompRate { get; set; }
        public Nullable<int> CrewHeadCount { get; set; }
        public Nullable<decimal> OnSiteMhs { get; set; }
        public Nullable<decimal> CrewLoadMhs { get; set; }
        public Nullable<decimal> CrewDriveMhs { get; set; }
        public Nullable<decimal> CrewTotMhs { get; set; }
        public Nullable<decimal> LoadMhPct { get; set; }
        public Nullable<decimal> DriveMhPct { get; set; }
    }
}
