//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPFPCost
    {
        public int PFPId { get; set; }
        public string PPFShortName { get; set; }
        public decimal MaterialCost { get; set; }
        public Nullable<decimal> MaterialMarkup { get; set; }
        public decimal ConcreteCost { get; set; }
        public Nullable<decimal> TotalMaterialCost { get; set; }
        public Nullable<decimal> TotalMhsBid { get; set; }
        public Nullable<decimal> OnsiteLbrCost { get; set; }
        public Nullable<decimal> LoadLbrCost { get; set; }
        public Nullable<decimal> DriveLbrCost { get; set; }
        public Nullable<decimal> TotalDollarsPaid { get; set; }
        public decimal SupervisonMarkup { get; set; }
        public Nullable<decimal> SupervisorLabor { get; set; }
        public Nullable<decimal> LaborMarkup { get; set; }
        public Nullable<decimal> TotalLaborCost { get; set; }
        public Nullable<decimal> EquipCost { get; set; }
        public Nullable<decimal> BenefitCost { get; set; }
        public Nullable<decimal> RetirementCost { get; set; }
        public Nullable<decimal> PayrollTaxCost { get; set; }
        public Nullable<decimal> WorkCompCost { get; set; }
        public Nullable<decimal> TotalIndirectCost { get; set; }
        public Nullable<decimal> JobCost { get; set; }
        public decimal PFPJobMarkup { get; set; }
        public Nullable<decimal> SuggestedSoldFor { get; set; }
        public decimal Divider { get; set; }
        public Nullable<decimal> SuggestedPerFootSoldFor { get; set; }
    }
}
