//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPFPMaterialOnlyPrice
    {
        public int PFPId { get; set; }
        public Nullable<decimal> GeoDrawMatPricingCost { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL1 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL2 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL3 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL4 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL5 { get; set; }
    }
}
