//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MAS_Imp_MiscChrgCode
    {
        public string ShopLbrID { get; set; }
        public string ShopLbrDesc { get; set; }
        public Nullable<decimal> ShopLbrCost { get; set; }
        public string Sort { get; set; }
        public string AccountKey_DirectLbr { get; set; }
        public Nullable<int> ShopLbrDescLen { get; set; }
    }
}
