//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MAS_Imp_InvMaster
    {
        public string Item_Number { get; set; }
        public string Product_Line { get; set; }
        public string StdUM { get; set; }
        public string PurchaseUM { get; set; }
        public string SalesUM { get; set; }
        public string ExtendedDescription { get; set; }
        public string Category1 { get; set; }
        public string Description { get; set; }
        public decimal Standard_Cost { get; set; }
        public string ProcurementTypeID { get; set; }
        public Nullable<decimal> Standard_Pricing { get; set; }
        public decimal Weight { get; set; }
    }
}
