//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MAS_Imp_BomSinglePass
    {
        public string BILL_NUMBER { get; set; }
        public string ITEM_CODE { get; set; }
        public string MISC_GL_ACCNT { get; set; }
        public Nullable<decimal> QTY_PER_BILL { get; set; }
        public string DESCRIP_1 { get; set; }
        public string MISC_CHRG_DESC { get; set; }
    }
}
