//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AtlasEntities : DbContext
    {
        public AtlasEntities()
            : base("name=AtlasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<A_CommonFieldNamesDataTypes> A_CommonFieldNamesDataTypes { get; set; }
        public DbSet<BID01_Headers> BID01_Headers { get; set; }
        public DbSet<BID02_LaborItems> BID02_LaborItems { get; set; }
        public DbSet<BID03_MaterialHeader> BID03_MaterialHeader { get; set; }
        public DbSet<BID04_MaterialDetail> BID04_MaterialDetail { get; set; }
        public DbSet<BID06_CrewProfile> BID06_CrewProfile { get; set; }
        public DbSet<BID07_Concrete> BID07_Concrete { get; set; }
        public DbSet<BID08_OtherCosts> BID08_OtherCosts { get; set; }
        public DbSet<BID09_EquipmentBurden> BID09_EquipmentBurden { get; set; }
        public DbSet<BID10_Status> BID10_Status { get; set; }
        public DbSet<BID11_Notes> BID11_Notes { get; set; }
        public DbSet<BID12_PFQHeader> BID12_PFQHeader { get; set; }
        public DbSet<BID13_PFQMaterial> BID13_PFQMaterial { get; set; }
        public DbSet<BID14_PFQLabor> BID14_PFQLabor { get; set; }
        public DbSet<BID15_PFQEquipmentBurden> BID15_PFQEquipmentBurden { get; set; }
        public DbSet<BID16_PFQCrewProfile> BID16_PFQCrewProfile { get; set; }
        public DbSet<BID17_PFQConcrete> BID17_PFQConcrete { get; set; }
        public DbSet<BID18_PFQOtherCosts> BID18_PFQOtherCosts { get; set; }
        public DbSet<BOM01_Headers> BOM01_Headers { get; set; }
        public DbSet<BOM02_MaterialBills> BOM02_MaterialBills { get; set; }
        public DbSet<BOM03_LaborRoutings> BOM03_LaborRoutings { get; set; }
        public DbSet<FRM01_TableFormName> FRM01_TableFormName { get; set; }
        public DbSet<GUI01_LbrFrmTypes> GUI01_LbrFrmTypes { get; set; }
        public DbSet<GUI02_LaborFormParams> GUI02_LaborFormParams { get; set; }
        public DbSet<INV01_Master> INV01_Master { get; set; }
        public DbSet<INV02_ProdLines> INV02_ProdLines { get; set; }
        public DbSet<INV03_CatalogLayout> INV03_CatalogLayout { get; set; }
        public DbSet<INV04_Class> INV04_Class { get; set; }
        public DbSet<INV05_SubClass> INV05_SubClass { get; set; }
        public DbSet<INV06_ProcurementTypes> INV06_ProcurementTypes { get; set; }
        public DbSet<INV07_UnitOfMeasure> INV07_UnitOfMeasure { get; set; }
        public DbSet<INV09_MasterPricingFamilies> INV09_MasterPricingFamilies { get; set; }
        public DbSet<INV10_MasVendorPricing> INV10_MasVendorPricing { get; set; }
        public DbSet<INV11_VendorPartNumCrossRef> INV11_VendorPartNumCrossRef { get; set; }
        public DbSet<INV12_ImageFiles> INV12_ImageFiles { get; set; }
        public DbSet<INV13_ImageFileTypes> INV13_ImageFileTypes { get; set; }
        public DbSet<INV15_WebSiteDetails> INV15_WebSiteDetails { get; set; }
        public DbSet<INV18_Color> INV18_Color { get; set; }
        public DbSet<PFP01_Header> PFP01_Header { get; set; }
        public DbSet<PFP02_Material> PFP02_Material { get; set; }
        public DbSet<PFP03_Labor> PFP03_Labor { get; set; }
        public DbSet<PFP04_Concrete> PFP04_Concrete { get; set; }
        public DbSet<PFP10_Catagory> PFP10_Catagory { get; set; }
        public DbSet<PFP11_ComponentType> PFP11_ComponentType { get; set; }
        public DbSet<PRJ01_Headers> PRJ01_Headers { get; set; }
        public DbSet<PRJ02_ContractPg> PRJ02_ContractPg { get; set; }
        public DbSet<PRJ03_ContractVerbiage> PRJ03_ContractVerbiage { get; set; }
        public DbSet<PRJ04_JobSites> PRJ04_JobSites { get; set; }
        public DbSet<PRJ05_JobStatus> PRJ05_JobStatus { get; set; }
        public DbSet<PRJ06_LedSource> PRJ06_LedSource { get; set; }
        public DbSet<PRJ07_BillingType> PRJ07_BillingType { get; set; }
        public DbSet<PRJ08_BillingInfo> PRJ08_BillingInfo { get; set; }
        public DbSet<PRL01_Employees> PRL01_Employees { get; set; }
        public DbSet<PRL07_TimeEntryHeader> PRL07_TimeEntryHeader { get; set; }
        public DbSet<PRL08_TimeEntryDetail> PRL08_TimeEntryDetail { get; set; }
        public DbSet<PRL09_TimeEntryMhs> PRL09_TimeEntryMhs { get; set; }
        public DbSet<SAL01_Company> SAL01_Company { get; set; }
        public DbSet<SAL02_Contacts> SAL02_Contacts { get; set; }
        public DbSet<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
        public DbSet<SAL05_Notes> SAL05_Notes { get; set; }
        public DbSet<SAL06_ActionTaken> SAL06_ActionTaken { get; set; }
        public DbSet<SAL10_SalesTypes> SAL10_SalesTypes { get; set; }
        public DbSet<Setup00_EarningCodes> Setup00_EarningCodes { get; set; }
        public DbSet<SetUp00_PayrollTaxes> SetUp00_PayrollTaxes { get; set; }
        public DbSet<Setup00_ProductionCodes> Setup00_ProductionCodes { get; set; }
        public DbSet<Setup00_WorkCompRates> Setup00_WorkCompRates { get; set; }
        public DbSet<Setup01_ConstructionType> Setup01_ConstructionType { get; set; }
        public DbSet<Setup01_Divisions> Setup01_Divisions { get; set; }
        public DbSet<Setup02_MhRates> Setup02_MhRates { get; set; }
        public DbSet<Setup03_DefaultCrewSize> Setup03_DefaultCrewSize { get; set; }
        public DbSet<Setup04_DefaultCrewEquipment> Setup04_DefaultCrewEquipment { get; set; }
        public DbSet<Setup10_EquipmentCosts> Setup10_EquipmentCosts { get; set; }
        public DbSet<Setup11_OtherCostTypes> Setup11_OtherCostTypes { get; set; }
        public DbSet<Setup23_FieldLaborTypes> Setup23_FieldLaborTypes { get; set; }
        public DbSet<Setup24_FieldLaborDetails> Setup24_FieldLaborDetails { get; set; }
        public DbSet<Setup25_FenceFamily> Setup25_FenceFamily { get; set; }
        public DbSet<Setup25_FenceTypes> Setup25_FenceTypes { get; set; }
        public DbSet<Setup26_FenceHts> Setup26_FenceHts { get; set; }
        public DbSet<Setup27_FootageRanges> Setup27_FootageRanges { get; set; }
        public DbSet<Setup28_FencePostTypes> Setup28_FencePostTypes { get; set; }
        public DbSet<Setup30_DigTypes> Setup30_DigTypes { get; set; }
        public DbSet<Setup31_ShopLocations> Setup31_ShopLocations { get; set; }
        public DbSet<Setup32_ShopLabors> Setup32_ShopLabors { get; set; }
        public DbSet<Setup96_TaxCalcTypes> Setup96_TaxCalcTypes { get; set; }
        public DbSet<Setup97_ZipCodes> Setup97_ZipCodes { get; set; }
        public DbSet<Setup98_SalesCommissions> Setup98_SalesCommissions { get; set; }
        public DbSet<TempLaborDetail> TempLaborDetails { get; set; }
        public DbSet<v_aTableNames> v_aTableNames { get; set; }
        public DbSet<vBIDConcreteCost> vBIDConcreteCosts { get; set; }
        public DbSet<vBIDCrewRate> vBIDCrewRates { get; set; }
        public DbSet<vBIDCrewTimeSheetComplete> vBIDCrewTimeSheetCompletes { get; set; }
        public DbSet<vBIDCrewTimeSheetDrive> vBIDCrewTimeSheetDrives { get; set; }
        public DbSet<vBIDCrewTimeSheetLoad> vBIDCrewTimeSheetLoads { get; set; }
        public DbSet<vBIDCrewTimeSheetOnsite> vBIDCrewTimeSheetOnsites { get; set; }
        public DbSet<vBIDCrewTimeSheetReport> vBIDCrewTimeSheetReports { get; set; }
        public DbSet<vBIDEquipmentCost> vBIDEquipmentCosts { get; set; }
        public DbSet<vBIDLaborCost> vBIDLaborCosts { get; set; }
        public DbSet<vBIDMaterialCost> vBIDMaterialCosts { get; set; }
        public DbSet<vBIDMhsOnsite> vBIDMhsOnsites { get; set; }
        public DbSet<vBIDMhsOnsiteDetail> vBIDMhsOnsiteDetails { get; set; }
        public DbSet<vBIDOtherCost> vBIDOtherCosts { get; set; }
        public DbSet<vBIDPreBid> vBIDPreBids { get; set; }
        public DbSet<vBIDPreBidRollUp> vBIDPreBidRollUps { get; set; }
        public DbSet<vBIDSubTimeSheetComplete> vBIDSubTimeSheetCompletes { get; set; }
        public DbSet<vBIDSubTimeSheetDrive> vBIDSubTimeSheetDrives { get; set; }
        public DbSet<vBIDSubTimeSheetLoad> vBIDSubTimeSheetLoads { get; set; }
        public DbSet<vBIDSubTimeSheetOnsite> vBIDSubTimeSheetOnsites { get; set; }
        public DbSet<vBIDSubTimeSheetReport> vBIDSubTimeSheetReports { get; set; }
        public DbSet<vBOMCombinedDetail> vBOMCombinedDetails { get; set; }
        public DbSet<vBOMCostLbr> vBOMCostLbrs { get; set; }
        public DbSet<vBOMCostMat> vBOMCostMats { get; set; }
        public DbSet<vBOMCostTotal> vBOMCostTotals { get; set; }
        public DbSet<vBOMMasCalcBurden> vBOMMasCalcBurdens { get; set; }
        public DbSet<vBOMMissingLbrCost> vBOMMissingLbrCosts { get; set; }
        public DbSet<vBOMMissingMatCost> vBOMMissingMatCosts { get; set; }
        public DbSet<vBOMReport> vBOMReports { get; set; }
        public DbSet<vBOMUpdateInventoryCostsAndWt> vBOMUpdateInventoryCostsAndWts { get; set; }
        public DbSet<vCatalogPricing> vCatalogPricings { get; set; }
        public DbSet<vCrewCostSummary> vCrewCostSummaries { get; set; }
        public DbSet<vEstCellularGateDouble> vEstCellularGateDoubles { get; set; }
        public DbSet<vEstCellularGateSingle> vEstCellularGateSingles { get; set; }
        public DbSet<vEstCellularPanel> vEstCellularPanels { get; set; }
        public DbSet<vEstCellularPostBlank> vEstCellularPostBlanks { get; set; }
        public DbSet<vEstCellularPostCap> vEstCellularPostCaps { get; set; }
        public DbSet<vEstCellularPostCorner> vEstCellularPostCorners { get; set; }
        public DbSet<vEstCellularPostEnd> vEstCellularPostEnds { get; set; }
        public DbSet<vEstCellularPostLine> vEstCellularPostLines { get; set; }
        public DbSet<vEstChainLinkBarbedWire> vEstChainLinkBarbedWires { get; set; }
        public DbSet<vEstChainLinkBoulevardClamp> vEstChainLinkBoulevardClamps { get; set; }
        public DbSet<vEstChainLinkBraceBand> vEstChainLinkBraceBands { get; set; }
        public DbSet<vEstChainLinkCarriageBolt> vEstChainLinkCarriageBolts { get; set; }
        public DbSet<vEstChainLinkFenceSlat> vEstChainLinkFenceSlats { get; set; }
        public DbSet<vEstChainLinkGateCantilever> vEstChainLinkGateCantilevers { get; set; }
        public DbSet<vEstChainLinkGateCloser> vEstChainLinkGateClosers { get; set; }
        public DbSet<vEstChainLinkGateDropRod> vEstChainLinkGateDropRods { get; set; }
        public DbSet<vEstChainLinkGateHingeAssembly> vEstChainLinkGateHingeAssemblies { get; set; }
        public DbSet<vEstChainLinkGateHingeFemale> vEstChainLinkGateHingeFemales { get; set; }
        public DbSet<vEstChainLinkGateHingeMale> vEstChainLinkGateHingeMales { get; set; }
        public DbSet<vEstChainLinkGateLatchAssembly> vEstChainLinkGateLatchAssemblies { get; set; }
        public DbSet<vEstChainLinkGateLatchCollar> vEstChainLinkGateLatchCollars { get; set; }
        public DbSet<vEstChainLinkGateLatchFork> vEstChainLinkGateLatchForks { get; set; }
        public DbSet<vEstChainLinkGateRollerCantilever> vEstChainLinkGateRollerCantilevers { get; set; }
        public DbSet<vEstChainLinkGateSwing> vEstChainLinkGateSwings { get; set; }
        public DbSet<vEstChainLinkHogRing> vEstChainLinkHogRings { get; set; }
        public DbSet<vEstChainLinkLinePost> vEstChainLinkLinePosts { get; set; }
        public DbSet<vEstChainLinkLinePostTie> vEstChainLinkLinePostTies { get; set; }
        public DbSet<vEstChainLinkLinePostTopBWA> vEstChainLinkLinePostTopBWAs { get; set; }
        public DbSet<vEstChainLinkLinePostTopLoopCap> vEstChainLinkLinePostTopLoopCaps { get; set; }
        public DbSet<vEstChainLinkPostBase> vEstChainLinkPostBases { get; set; }
        public DbSet<vEstChainLinkRailEnd> vEstChainLinkRailEnds { get; set; }
        public DbSet<vEstChainLinkTensionBand> vEstChainLinkTensionBands { get; set; }
        public DbSet<vEstChainLinkTensionBar> vEstChainLinkTensionBars { get; set; }
        public DbSet<vEstChainLinkTensionWire> vEstChainLinkTensionWires { get; set; }
        public DbSet<vEstChainLinkTermPost> vEstChainLinkTermPosts { get; set; }
        public DbSet<vEstChainLinkTopRail> vEstChainLinkTopRails { get; set; }
        public DbSet<vEstChainLinkTopRailSleeve> vEstChainLinkTopRailSleeves { get; set; }
        public DbSet<vEstChainLinkTrussRod> vEstChainLinkTrussRods { get; set; }
        public DbSet<vEstChainLinkTrussRodTightener> vEstChainLinkTrussRodTighteners { get; set; }
        public DbSet<vEstChainLinkWire> vEstChainLinkWires { get; set; }
        public DbSet<vEstOrnaGateSingle> vEstOrnaGateSingles { get; set; }
        public DbSet<vEstOrnaPanel> vEstOrnaPanels { get; set; }
        public DbSet<vEstPVCGateCloser> vEstPVCGateClosers { get; set; }
        public DbSet<vEstPVCGateDouble> vEstPVCGateDoubles { get; set; }
        public DbSet<vEstPVCGateDropRod> vEstPVCGateDropRods { get; set; }
        public DbSet<vEstPVCGateHinge> vEstPVCGateHinges { get; set; }
        public DbSet<vEstPVCGateLatch> vEstPVCGateLatches { get; set; }
        public DbSet<vEstPVCGateSingle> vEstPVCGateSingles { get; set; }
        public DbSet<vEstPVCPanel> vEstPVCPanels { get; set; }
        public DbSet<vEstPVCPostBlank> vEstPVCPostBlanks { get; set; }
        public DbSet<vEstPVCPostCap> vEstPVCPostCaps { get; set; }
        public DbSet<vEstPVCPostCorner> vEstPVCPostCorners { get; set; }
        public DbSet<vEstPVCPostEnd> vEstPVCPostEnds { get; set; }
        public DbSet<vEstPVCPostLine> vEstPVCPostLines { get; set; }
        public DbSet<vEstPVCPostStiffener> vEstPVCPostStiffeners { get; set; }
        public DbSet<vEstWoodCellularGateCloser> vEstWoodCellularGateClosers { get; set; }
        public DbSet<vEstWoodCellularGateDropRod> vEstWoodCellularGateDropRods { get; set; }
        public DbSet<vEstWoodCellularGateHinge> vEstWoodCellularGateHinges { get; set; }
        public DbSet<vEstWoodCellularGateLatch> vEstWoodCellularGateLatches { get; set; }
        public DbSet<vEstWoodGateDouble> vEstWoodGateDoubles { get; set; }
        public DbSet<vEstWoodGateSingle> vEstWoodGateSingles { get; set; }
        public DbSet<vEstWoodPanel> vEstWoodPanels { get; set; }
        public DbSet<vEstWoodPostBlank> vEstWoodPostBlanks { get; set; }
        public DbSet<vEstWoodPostCap> vEstWoodPostCaps { get; set; }
        public DbSet<vEstWoodPostCorner> vEstWoodPostCorners { get; set; }
        public DbSet<vEstWoodPostEnd> vEstWoodPostEnds { get; set; }
        public DbSet<vEstWoodPostLine> vEstWoodPostLines { get; set; }
        public DbSet<vGeoDrawPricing> vGeoDrawPricings { get; set; }
        public DbSet<vGeoDrawPricingGateDouble> vGeoDrawPricingGateDoubles { get; set; }
        public DbSet<vGeoDrawPricingGateSingle> vGeoDrawPricingGateSingles { get; set; }
        public DbSet<vGeoDrawPricingPanel> vGeoDrawPricingPanels { get; set; }
        public DbSet<vGeoDrawStyleSetup> vGeoDrawStyleSetups { get; set; }
        public DbSet<vPFPConcreteCost> vPFPConcreteCosts { get; set; }
        public DbSet<vPFPCost> vPFPCosts { get; set; }
        public DbSet<vPFPCrewRate> vPFPCrewRates { get; set; }
        public DbSet<vPFPEquipmentCost> vPFPEquipmentCosts { get; set; }
        public DbSet<vPFPLaborCost> vPFPLaborCosts { get; set; }
        public DbSet<vPFPMaterialCost> vPFPMaterialCosts { get; set; }
        public DbSet<vPFPMaterialOnlyPrice> vPFPMaterialOnlyPrices { get; set; }
        public DbSet<vPFPMhsOnsite> vPFPMhsOnsites { get; set; }
        public DbSet<vPFQConcreteCost> vPFQConcreteCosts { get; set; }
        public DbSet<vPFQConcreteCostDetail> vPFQConcreteCostDetails { get; set; }
        public DbSet<vPFQCrewRate> vPFQCrewRates { get; set; }
        public DbSet<vPFQCrewRatesDetail> vPFQCrewRatesDetails { get; set; }
        public DbSet<vPFQEquipCostByHeader> vPFQEquipCostByHeaders { get; set; }
        public DbSet<vPFQEquipmentCost> vPFQEquipmentCosts { get; set; }
        public DbSet<vPFQEquipmentCostDetail> vPFQEquipmentCostDetails { get; set; }
        public DbSet<vPFQLaborCost> vPFQLaborCosts { get; set; }
        public DbSet<vPFQLaborCostDetail> vPFQLaborCostDetails { get; set; }
        public DbSet<vPFQMaterialCost> vPFQMaterialCosts { get; set; }
        public DbSet<vPFQMaterialCostByPartNum> vPFQMaterialCostByPartNums { get; set; }
        public DbSet<vPFQMaterialCostDetail> vPFQMaterialCostDetails { get; set; }
        public DbSet<vPFQMhsOnsite> vPFQMhsOnsites { get; set; }
        public DbSet<vPFQMhsOnsiteDetail> vPFQMhsOnsiteDetails { get; set; }
        public DbSet<vPFQOtherCost> vPFQOtherCosts { get; set; }
        public DbSet<vPFQOtherCostDetail> vPFQOtherCostDetails { get; set; }
        public DbSet<vPFQPreBid> vPFQPreBids { get; set; }
        public DbSet<vPFQPrebidDetail> vPFQPrebidDetails { get; set; }
        public DbSet<vw_MAS_Imp_BomBurden> vw_MAS_Imp_BomBurden { get; set; }
        public DbSet<vw_MAS_Imp_BomLbr> vw_MAS_Imp_BomLbr { get; set; }
        public DbSet<vw_MAS_Imp_BomMaterial> vw_MAS_Imp_BomMaterial { get; set; }
        public DbSet<vw_MAS_Imp_Boms> vw_MAS_Imp_Boms { get; set; }
        public DbSet<vw_MAS_Imp_BomSinglePass> vw_MAS_Imp_BomSinglePass { get; set; }
        public DbSet<vw_MAS_Imp_ExtDesc> vw_MAS_Imp_ExtDesc { get; set; }
        public DbSet<vw_MAS_Imp_ExtDescCI> vw_MAS_Imp_ExtDescCI { get; set; }
        public DbSet<vw_MAS_Imp_InvMaster> vw_MAS_Imp_InvMaster { get; set; }
        public DbSet<vw_MAS_Imp_InvPricing> vw_MAS_Imp_InvPricing { get; set; }
        public DbSet<vw_MAS_Imp_LvlPricing> vw_MAS_Imp_LvlPricing { get; set; }
        public DbSet<vw_MAS_Imp_MiscChrgCode> vw_MAS_Imp_MiscChrgCode { get; set; }
        public DbSet<vw_MAS_Imp_VendorPricing> vw_MAS_Imp_VendorPricing { get; set; }
    
        [EdmFunction("Entities", "fn_ExampleTableFunction")]
        public virtual IQueryable<fn_ExampleTableFunction_Result> fn_ExampleTableFunction(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ExampleTableFunction_Result>("[Entities].[fn_ExampleTableFunction](@StartDate, @EndDate)", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spCRM_Comp_Ins_Result> spCRM_Comp_Ins(string company, string address, string city, string state, string zip, string phone, string ext, string fax, string mobile, string eMail, Nullable<System.DateTime> dateEntered, Nullable<bool> activeFlag)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("Zip", zip) :
                new ObjectParameter("Zip", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var extParameter = ext != null ?
                new ObjectParameter("Ext", ext) :
                new ObjectParameter("Ext", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("Fax", fax) :
                new ObjectParameter("Fax", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var eMailParameter = eMail != null ?
                new ObjectParameter("EMail", eMail) :
                new ObjectParameter("EMail", typeof(string));
    
            var dateEnteredParameter = dateEntered.HasValue ?
                new ObjectParameter("DateEntered", dateEntered) :
                new ObjectParameter("DateEntered", typeof(System.DateTime));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCRM_Comp_Ins_Result>("spCRM_Comp_Ins", companyParameter, addressParameter, cityParameter, stateParameter, zipParameter, phoneParameter, extParameter, faxParameter, mobileParameter, eMailParameter, dateEnteredParameter, activeFlagParameter);
        }
    
        public virtual ObjectResult<spddl_Company_Result> spddl_Company()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spddl_Company_Result>("spddl_Company");
        }
    
        public virtual ObjectResult<spddl_CompanyId_Result> spddl_CompanyId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spddl_CompanyId_Result>("spddl_CompanyId");
        }
    
        public virtual ObjectResult<spddl_LedSources_Result> spddl_LedSources()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spddl_LedSources_Result>("spddl_LedSources");
        }
    
        public virtual ObjectResult<spddl_State_Result> spddl_State()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spddl_State_Result>("spddl_State");
        }
    
        public virtual ObjectResult<spFilterPFP01_Result> spFilterPFP01(Nullable<int> fenceTypeID, Nullable<int> pFPCatId, Nullable<int> fenceHtID)
        {
            var fenceTypeIDParameter = fenceTypeID.HasValue ?
                new ObjectParameter("FenceTypeID", fenceTypeID) :
                new ObjectParameter("FenceTypeID", typeof(int));
    
            var pFPCatIdParameter = pFPCatId.HasValue ?
                new ObjectParameter("PFPCatId", pFPCatId) :
                new ObjectParameter("PFPCatId", typeof(int));
    
            var fenceHtIDParameter = fenceHtID.HasValue ?
                new ObjectParameter("FenceHtID", fenceHtID) :
                new ObjectParameter("FenceHtID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFilterPFP01_Result>("spFilterPFP01", fenceTypeIDParameter, pFPCatIdParameter, fenceHtIDParameter);
        }
    
        public virtual ObjectResult<spGetCityInfo_Result> spGetCityInfo(string zipcode)
        {
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCityInfo_Result>("spGetCityInfo", zipcodeParameter);
        }
    
        public virtual ObjectResult<spGetConcreteCost_Result> spGetConcreteCost(string partNum)
        {
            var partNumParameter = partNum != null ?
                new ObjectParameter("PartNum", partNum) :
                new ObjectParameter("PartNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConcreteCost_Result>("spGetConcreteCost", partNumParameter);
        }
    
        public virtual ObjectResult<spGetCrewProfileDetail_Result> spGetCrewProfileDetail(Nullable<int> bIDID)
        {
            var bIDIDParameter = bIDID.HasValue ?
                new ObjectParameter("BIDID", bIDID) :
                new ObjectParameter("BIDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCrewProfileDetail_Result>("spGetCrewProfileDetail", bIDIDParameter);
        }
    
        public virtual ObjectResult<spGetDefaultDriveTimes_Result> spGetDefaultDriveTimes(string mhRateID)
        {
            var mhRateIDParameter = mhRateID != null ?
                new ObjectParameter("MhRateID", mhRateID) :
                new ObjectParameter("MhRateID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDefaultDriveTimes_Result>("spGetDefaultDriveTimes", mhRateIDParameter);
        }
    
        public virtual ObjectResult<spGetEquipCost_Result> spGetEquipCost(Nullable<int> equipCostID)
        {
            var equipCostIDParameter = equipCostID.HasValue ?
                new ObjectParameter("EquipCostID", equipCostID) :
                new ObjectParameter("EquipCostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetEquipCost_Result>("spGetEquipCost", equipCostIDParameter);
        }
    
        public virtual ObjectResult<spGetFenceTypeMarkups_Result> spGetFenceTypeMarkups(Nullable<int> fenceTypeID)
        {
            var fenceTypeIDParameter = fenceTypeID.HasValue ?
                new ObjectParameter("FenceTypeID", fenceTypeID) :
                new ObjectParameter("FenceTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFenceTypeMarkups_Result>("spGetFenceTypeMarkups", fenceTypeIDParameter);
        }
    
        public virtual ObjectResult<spGetLaborModDigTypes_Result> spGetLaborModDigTypes(Nullable<int> digTypeID)
        {
            var digTypeIDParameter = digTypeID.HasValue ?
                new ObjectParameter("DigTypeID", digTypeID) :
                new ObjectParameter("DigTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLaborModDigTypes_Result>("spGetLaborModDigTypes", digTypeIDParameter);
        }
    
        public virtual ObjectResult<spGetLaborModFenceHt_Result> spGetLaborModFenceHt(Nullable<int> fenceHtID)
        {
            var fenceHtIDParameter = fenceHtID.HasValue ?
                new ObjectParameter("FenceHtID", fenceHtID) :
                new ObjectParameter("FenceHtID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLaborModFenceHt_Result>("spGetLaborModFenceHt", fenceHtIDParameter);
        }
    
        public virtual ObjectResult<spGetLaborModFenceRange_Result> spGetLaborModFenceRange(Nullable<int> ftRangeID)
        {
            var ftRangeIDParameter = ftRangeID.HasValue ?
                new ObjectParameter("FtRangeID", ftRangeID) :
                new ObjectParameter("FtRangeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLaborModFenceRange_Result>("spGetLaborModFenceRange", ftRangeIDParameter);
        }
    
        public virtual ObjectResult<spGetLaborModRules_Result> spGetLaborModRules(Nullable<int> fieldLbrDtlsID)
        {
            var fieldLbrDtlsIDParameter = fieldLbrDtlsID.HasValue ?
                new ObjectParameter("FieldLbrDtlsID", fieldLbrDtlsID) :
                new ObjectParameter("FieldLbrDtlsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLaborModRules_Result>("spGetLaborModRules", fieldLbrDtlsIDParameter);
        }
    
        public virtual ObjectResult<spGetOtherCost_Result> spGetOtherCost(Nullable<int> otherCostTypeID)
        {
            var otherCostTypeIDParameter = otherCostTypeID.HasValue ?
                new ObjectParameter("OtherCostTypeID", otherCostTypeID) :
                new ObjectParameter("OtherCostTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetOtherCost_Result>("spGetOtherCost", otherCostTypeIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spGetPayRollPerTot()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spGetPayRollPerTot");
        }
    
        public virtual ObjectResult<Nullable<decimal>> spGetPFPDivider(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spGetPFPDivider", pFPIdParameter);
        }
    
        public virtual ObjectResult<spGetPFQConcreteDetail_Result> spGetPFQConcreteDetail(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPFQConcreteDetail_Result>("spGetPFQConcreteDetail", pFPIdParameter);
        }
    
        public virtual ObjectResult<spGetPFQEquipmentBurdenDetail_Result> spGetPFQEquipmentBurdenDetail(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPFQEquipmentBurdenDetail_Result>("spGetPFQEquipmentBurdenDetail", pFPIdParameter);
        }
    
        public virtual ObjectResult<spGetPFQLaborDetail_Result> spGetPFQLaborDetail(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPFQLaborDetail_Result>("spGetPFQLaborDetail", pFPIdParameter);
        }
    
        public virtual ObjectResult<spGetPFQMaterialDetail_Result> spGetPFQMaterialDetail(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPFQMaterialDetail_Result>("spGetPFQMaterialDetail", pFPIdParameter);
        }
    
        public virtual ObjectResult<spGetSalesTax_Result> spGetSalesTax(Nullable<int> taxCalcTypeID)
        {
            var taxCalcTypeIDParameter = taxCalcTypeID.HasValue ?
                new ObjectParameter("TaxCalcTypeID", taxCalcTypeID) :
                new ObjectParameter("TaxCalcTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSalesTax_Result>("spGetSalesTax", taxCalcTypeIDParameter);
        }
    
        public virtual ObjectResult<spPFPCostDetail_Result> spPFPCostDetail(Nullable<int> pFPId)
        {
            var pFPIdParameter = pFPId.HasValue ?
                new ObjectParameter("PFPId", pFPId) :
                new ObjectParameter("PFPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPFPCostDetail_Result>("spPFPCostDetail", pFPIdParameter);
        }
    }
}
