//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID03_MaterialHeader
    {
        public BID03_MaterialHeader()
        {
            this.BID04_MaterialDetail = new HashSet<BID04_MaterialDetail>();
        }
    
        public int BIDMatHeaderID { get; set; }
        public int BIDID { get; set; }
        public byte ImportedFlag { get; set; }
        public string CfsFileName { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string EmployeeID { get; set; }
        public byte OverRideCost { get; set; }
        public decimal OverRiddenCost { get; set; }
        public string Notes { get; set; }
    
        public virtual BID01_Headers BID01_Headers { get; set; }
        public virtual PRL01_Employees PRL01_Employees { get; set; }
        public virtual ICollection<BID04_MaterialDetail> BID04_MaterialDetail { get; set; }
    }
}
