//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID02_LaborItems
    {
        public int BIDLaborItemsID { get; set; }
        public int BIDID { get; set; }
        public int FieldLbrDtlsID { get; set; }
        public decimal Qty { get; set; }
        public decimal FieldLbrMhs { get; set; }
        public string FieldLbrUom { get; set; }
        public int ModifyByFenceHt { get; set; }
        public int ModifyByFootageRange { get; set; }
        public int ModifyByDigType { get; set; }
        public int Location { get; set; }
        public int FormParamId { get; set; }
    
        public virtual BID01_Headers BID01_Headers { get; set; }
        public virtual Setup24_FieldLaborDetails Setup24_FieldLaborDetails { get; set; }
    }
}
