//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID17_PFQConcrete
    {
        public int PFQConcID { get; set; }
        public int PFQHeaderID { get; set; }
        public string ConcreteType { get; set; }
        public int HoleQty { get; set; }
        public int HoleDia { get; set; }
        public int HoleDepth { get; set; }
        public Nullable<decimal> CalcYds { get; set; }
        public decimal RoundFactor { get; set; }
        public Nullable<decimal> BidYds { get; set; }
        public Nullable<decimal> CostPerYd { get; set; }
        public Nullable<decimal> ExtConcCost { get; set; }
    
        public virtual BID12_PFQHeader BID12_PFQHeader { get; set; }
    }
}
