//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID10_Status
    {
        public BID10_Status()
        {
            this.BID01_Headers = new HashSet<BID01_Headers>();
        }
    
        public string BIStatID { get; set; }
        public string BIStatDesc { get; set; }
    
        public virtual ICollection<BID01_Headers> BID01_Headers { get; set; }
    }
}
