//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BID11_Notes
    {
        public int BIDNotesID { get; set; }
        public string BIDTableName { get; set; }
        public int BIDID { get; set; }
        public string BINotes { get; set; }
    }
}
