//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM03_LaborRoutings
    {
        public int BomLaborID { get; set; }
        public string BomPartNum { get; set; }
        public string ShopLbrID { get; set; }
        public decimal OptimumBomLaborQty { get; set; }
        public decimal InefficiencyFactor { get; set; }
        public string BomCompTypeID { get; set; }
        public Nullable<decimal> BomLaborQty { get; set; }
    
        public virtual BOM01_Headers BOM01_Headers { get; set; }
        public virtual Setup32_ShopLabors Setup32_ShopLabors { get; set; }
    }
}
