//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM02_MaterialBills
    {
        public int BomMaterialID { get; set; }
        public string BomPartNum { get; set; }
        public string CompPartNum { get; set; }
        public decimal OptimumBomMaterialQty { get; set; }
        public decimal ScrapPercent { get; set; }
        public string BomCompTypeID { get; set; }
        public Nullable<decimal> BomMaterialQty { get; set; }
    
        public virtual BOM01_Headers BOM01_Headers { get; set; }
        public virtual INV01_Master INV01_Master { get; set; }
    }
}
