//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV04_Class
    {
        public INV04_Class()
        {
            this.INV05_SubClass = new HashSet<INV05_SubClass>();
        }
    
        public string ClassID { get; set; }
        public string Class { get; set; }
        public string CatLocID { get; set; }
        public byte InCatalogClass { get; set; }
        public decimal ClassSort { get; set; }
    
        public virtual INV03_CatalogLayout INV03_CatalogLayout { get; set; }
        public virtual ICollection<INV05_SubClass> INV05_SubClass { get; set; }
    }
}
