//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV09_MasterPricingFamilies
    {
        public INV09_MasterPricingFamilies()
        {
            this.INV01_Master = new HashSet<INV01_Master>();
        }
    
        public decimal MpfId { get; set; }
        public string MpfName { get; set; }
        public Nullable<decimal> MpfCost { get; set; }
        public Nullable<System.DateTime> DateOfMpfChange { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> Active { get; set; }
        public string FirstofSeriesPartNum { get; set; }
    
        public virtual ICollection<INV01_Master> INV01_Master { get; set; }
    }
}
