//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV03_CatalogLayout
    {
        public INV03_CatalogLayout()
        {
            this.INV04_Class = new HashSet<INV04_Class>();
            this.PFP10_Catagory = new HashSet<PFP10_Catagory>();
        }
    
        public string CatLocID { get; set; }
        public string CatLoc { get; set; }
        public string ProdLineID { get; set; }
        public byte InCatalogLoc { get; set; }
        public Nullable<double> CatSort { get; set; }
    
        public virtual INV02_ProdLines INV02_ProdLines { get; set; }
        public virtual ICollection<INV04_Class> INV04_Class { get; set; }
        public virtual ICollection<PFP10_Catagory> PFP10_Catagory { get; set; }
    }
}
