//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV12_ImageFiles
    {
        public string ImageId { get; set; }
        public string RelatedPartNum { get; set; }
        public string FolderName { get; set; }
        public string DriveName { get; set; }
        public int GraphicsTypeId { get; set; }
        public string MarkForDeletion { get; set; }
    
        public virtual INV13_ImageFileTypes INV13_ImageFileTypes { get; set; }
    }
}
