//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV15_WebSiteDetails
    {
        public int WebSiteDetailID { get; set; }
        public string Web_SubClass_Name { get; set; }
        public string SubClassID { get; set; }
        public string WebsiteImageId { get; set; }
        public string TopNav { get; set; }
        public string LeftNav { get; set; }
        public string TypeNav { get; set; }
        public string MaterialNav { get; set; }
        public string Function1 { get; set; }
        public string Function2 { get; set; }
        public string Function3 { get; set; }
        public string Function4 { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public string Tag4 { get; set; }
        public string Tag5 { get; set; }
        public Nullable<byte> IncludeSubClassInPFP { get; set; }
    
        public virtual INV05_SubClass INV05_SubClass { get; set; }
    }
}
