//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV18_Color
    {
        public INV18_Color()
        {
            this.INV01_Master = new HashSet<INV01_Master>();
            this.PFP01_Header = new HashSet<PFP01_Header>();
        }
    
        public int ColorId { get; set; }
        public string ColorName { get; set; }
    
        public virtual ICollection<INV01_Master> INV01_Master { get; set; }
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
    }
}
