//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV13_ImageFileTypes
    {
        public INV13_ImageFileTypes()
        {
            this.INV12_ImageFiles = new HashSet<INV12_ImageFiles>();
        }
    
        public int GraphicsTypeId { get; set; }
        public string GraphicsTypeDesc { get; set; }
        public string PreFix { get; set; }
    
        public virtual ICollection<INV12_ImageFiles> INV12_ImageFiles { get; set; }
    }
}
