//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFP02_Material
    {
        public int PFPMatID { get; set; }
        public string PartNum { get; set; }
        public decimal Qty { get; set; }
        public int PFPId { get; set; }
        public string PFPBomType { get; set; }
    
        public virtual INV01_Master INV01_Master { get; set; }
        public virtual PFP01_Header PFP01_Header { get; set; }
    }
}
