//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFP10_Catagory
    {
        public PFP10_Catagory()
        {
            this.PFP01_Header = new HashSet<PFP01_Header>();
        }
    
        public int PFPCatId { get; set; }
        public string PFPCat { get; set; }
        public int PFPCatSort { get; set; }
        public string CatLocID { get; set; }
        public byte InGeoDraw { get; set; }
    
        public virtual INV03_CatalogLayout INV03_CatalogLayout { get; set; }
        public virtual ICollection<PFP01_Header> PFP01_Header { get; set; }
    }
}
