//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ04_JobSites
    {
        public PRJ04_JobSites()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
    
        public int JobSiteId { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastOrCompanyName { get; set; }
        public string JobSiteAddress { get; set; }
        public string JobSiteCity { get; set; }
        public string JobSiteState { get; set; }
        public string JobSiteZip { get; set; }
        public string JobSitePhone { get; set; }
        public string JobSitePhoneExt { get; set; }
        public string JobSiteFax { get; set; }
        public string JobSiteMobilePhone { get; set; }
        public string JobSiteEMail { get; set; }
        public Nullable<int> SalApptId { get; set; }
    
        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
        public virtual SAL03_ResAppointments SAL03_ResAppointments { get; set; }
    }
}
