//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ07_BillingType
    {
        public PRJ07_BillingType()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
    
        public short BillingTypeID { get; set; }
        public string BillingTypeDesc { get; set; }
    
        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
    }
}
