//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ08_BillingInfo
    {
        public PRJ08_BillingInfo()
        {
            this.PRJ01_Headers = new HashSet<PRJ01_Headers>();
        }
    
        public int PRJBillingID { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastOrCompanyName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string BillingContPhone { get; set; }
        public string BillingContPhoneExt { get; set; }
        public string BillingFax { get; set; }
        public string BillingMobilePhone { get; set; }
        public string BillingEmail { get; set; }
    
        public virtual ICollection<PRJ01_Headers> PRJ01_Headers { get; set; }
    }
}
