//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ06_LedSource
    {
        public PRJ06_LedSource()
        {
            this.SAL02_Contacts = new HashSet<SAL02_Contacts>();
        }
    
        public int LedSourceId { get; set; }
        public string LedSourceName { get; set; }
    
        public virtual ICollection<SAL02_Contacts> SAL02_Contacts { get; set; }
    }
}
