//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRL09_TimeEntryMhs
    {
        public int LbrHrsId { get; set; }
        public int EntryId { get; set; }
        public string EmployeeId { get; set; }
        public byte PayCashInLieuOf { get; set; }
        public decimal Start { get; set; }
        public decimal OnSite { get; set; }
        public decimal OffSite { get; set; }
        public decimal Stop { get; set; }
        public decimal Lunch { get; set; }
        public bool DeductLunchFromOnSiteTime { get; set; }
        public Nullable<decimal> OnSiteMhs { get; set; }
        public Nullable<decimal> OffsiteMhs { get; set; }
        public Nullable<decimal> TotMhs { get; set; }
        public int HeadCount { get; set; }
        public decimal OnsiteRate { get; set; }
        public decimal OffsiteRate { get; set; }
        public decimal MinWageRate { get; set; }
    
        public virtual PRL01_Employees PRL01_Employees { get; set; }
        public virtual PRL07_TimeEntryHeader PRL07_TimeEntryHeader { get; set; }
    }
}
