//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL02_Contacts
    {
        public SAL02_Contacts()
        {
            this.SAL03_ResAppointments = new HashSet<SAL03_ResAppointments>();
        }
    
        public int SalContId { get; set; }
        public string SalContFirstName { get; set; }
        public string SalContLastName { get; set; }
        public string SalContAddress { get; set; }
        public string SalContCity { get; set; }
        public string SalContState { get; set; }
        public string SalContZip { get; set; }
        public string SalContPhone { get; set; }
        public string SalContPhoneExt { get; set; }
        public string SalContFax { get; set; }
        public string SalContMobile { get; set; }
        public string SalContEmail { get; set; }
        public string SalCompId { get; set; }
        public string SalContActiveFlag { get; set; }
        public Nullable<int> LedSourceId { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual PRJ06_LedSource PRJ06_LedSource { get; set; }
        public virtual SAL01_Company SAL01_Company { get; set; }
        public virtual ICollection<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
    }
}
