//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL01_Company
    {
        public SAL01_Company()
        {
            this.SAL02_Contacts = new HashSet<SAL02_Contacts>();
        }
    
        public string SalCompId { get; set; }
        public string SalCompName { get; set; }
        public string SalCompAddress { get; set; }
        public string SalCompCity { get; set; }
        public string SalCompState { get; set; }
        public string SalCompZip { get; set; }
        public string SalCompPhone { get; set; }
        public string SalCompPhoneExt { get; set; }
        public string SalCompFax { get; set; }
        public string SalCompMobile { get; set; }
        public string SalCompEMail { get; set; }
        public System.DateTime SalCompDateEntered { get; set; }
        public Nullable<bool> SalCompActiveFlag { get; set; }
    
        public virtual ICollection<SAL02_Contacts> SAL02_Contacts { get; set; }
    }
}
