//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL05_Notes
    {
        public SAL05_Notes()
        {
            this.SAL03_ResAppointments = new HashSet<SAL03_ResAppointments>();
        }
    
        public int SalNotesId { get; set; }
        public System.DateTime SalNotesDate { get; set; }
        public string SalNotes { get; set; }
        public string UserEntered { get; set; }
    
        public virtual ICollection<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
    }
}
