//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL03_ResAppointments
    {
        public SAL03_ResAppointments()
        {
            this.PRJ04_JobSites = new HashSet<PRJ04_JobSites>();
        }
    
        public int SalApptId { get; set; }
        public Nullable<int> SalContId { get; set; }
        public string SalApptFirstName { get; set; }
        public string SalApptLastName { get; set; }
        public string SalApptAddress { get; set; }
        public string SalApptCity { get; set; }
        public string SalApptState { get; set; }
        public string SalApptZip { get; set; }
        public string SalApptPhone { get; set; }
        public string SalApptMobile { get; set; }
        public string SalApptEmail { get; set; }
        public System.DateTime SalApptStartDate { get; set; }
        public string SalApptStartTime { get; set; }
        public System.DateTime SalApptEndDate { get; set; }
        public string SalApptEndTime { get; set; }
        public int FenceTypeID { get; set; }
        public string CommID { get; set; }
        public Nullable<int> SalNotesId { get; set; }
        public Nullable<int> SalTypeId { get; set; }
        public string ApptDesc { get; set; }
        public string SalApptUserEntered { get; set; }
    
        public virtual ICollection<PRJ04_JobSites> PRJ04_JobSites { get; set; }
        public virtual SAL02_Contacts SAL02_Contacts { get; set; }
        public virtual SAL05_Notes SAL05_Notes { get; set; }
        public virtual SAL10_SalesTypes SAL10_SalesTypes { get; set; }
        public virtual Setup25_FenceTypes Setup25_FenceTypes { get; set; }
        public virtual Setup98_SalesCommissions Setup98_SalesCommissions { get; set; }
    }
}
