//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup10_EquipmentCosts
    {
        public Setup10_EquipmentCosts()
        {
            this.BID09_EquipmentBurden = new HashSet<BID09_EquipmentBurden>();
            this.BID15_PFQEquipmentBurden = new HashSet<BID15_PFQEquipmentBurden>();
            this.Setup04_DefaultCrewEquipment = new HashSet<Setup04_DefaultCrewEquipment>();
        }
    
        public int EquipCostID { get; set; }
        public string EquipName { get; set; }
        public decimal EquipRatePerMhHr { get; set; }
    
        public virtual ICollection<BID09_EquipmentBurden> BID09_EquipmentBurden { get; set; }
        public virtual ICollection<BID15_PFQEquipmentBurden> BID15_PFQEquipmentBurden { get; set; }
        public virtual ICollection<Setup04_DefaultCrewEquipment> Setup04_DefaultCrewEquipment { get; set; }
    }
}
