//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup00_WorkCompRates
    {
        public Setup00_WorkCompRates()
        {
            this.Setup03_DefaultCrewSize = new HashSet<Setup03_DefaultCrewSize>();
        }
    
        public int WorkCompID { get; set; }
        public string WorkCompDesc { get; set; }
        public decimal WorkCompRate { get; set; }
        public byte CalcRegPay { get; set; }
        public byte CalcOtPay { get; set; }
        public byte CalcComm { get; set; }
        public byte CalcBenefitPay { get; set; }
        public int CalcCap { get; set; }
    
        public virtual ICollection<Setup03_DefaultCrewSize> Setup03_DefaultCrewSize { get; set; }
    }
}
