//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup23_FieldLaborTypes
    {
        public Setup23_FieldLaborTypes()
        {
            this.GUI02_LaborFormParams = new HashSet<GUI02_LaborFormParams>();
            this.Setup24_FieldLaborDetails = new HashSet<Setup24_FieldLaborDetails>();
        }
    
        public int FieldLbrTypeID { get; set; }
        public string FieldLbrTypeDesc { get; set; }
        public int FenceTypeID { get; set; }
        public Nullable<int> FenceFamilyId { get; set; }
        public double Sort { get; set; }
        public int ModifyByFenceHt { get; set; }
        public int ModifyByFootageRange { get; set; }
        public int ModifyByDigType { get; set; }
    
        public virtual ICollection<GUI02_LaborFormParams> GUI02_LaborFormParams { get; set; }
        public virtual Setup25_FenceFamily Setup25_FenceFamily { get; set; }
        public virtual ICollection<Setup24_FieldLaborDetails> Setup24_FieldLaborDetails { get; set; }
    }
}
