//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup00_ProductionCodes
    {
        public Setup00_ProductionCodes()
        {
            this.PRL08_TimeEntryDetail = new HashSet<PRL08_TimeEntryDetail>();
        }
    
        public int ProductionCodeID { get; set; }
        public string ProductionCode { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<PRL08_TimeEntryDetail> PRL08_TimeEntryDetail { get; set; }
    }
}
