//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup04_DefaultCrewEquipment
    {
        public int DefaultEquipID { get; set; }
        public int EquipCostID { get; set; }
        public int QtyBid { get; set; }
        public int FenceTypeID { get; set; }
    
        public virtual Setup10_EquipmentCosts Setup10_EquipmentCosts { get; set; }
        public virtual Setup25_FenceTypes Setup25_FenceTypes { get; set; }
    }
}
