//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup98_SalesCommissions
    {
        public Setup98_SalesCommissions()
        {
            this.SAL03_ResAppointments = new HashSet<SAL03_ResAppointments>();
        }
    
        public string CommID { get; set; }
        public string EmployeeID { get; set; }
        public decimal InstallCommRate { get; set; }
        public decimal OtcCommRate { get; set; }
        public byte InSalesReports { get; set; }
        public string Prefix { get; set; }
    
        public virtual PRL01_Employees PRL01_Employees { get; set; }
        public virtual ICollection<SAL03_ResAppointments> SAL03_ResAppointments { get; set; }
    }
}
