//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup32_ShopLabors
    {
        public Setup32_ShopLabors()
        {
            this.BOM03_LaborRoutings = new HashSet<BOM03_LaborRoutings>();
        }
    
        public string ShopLbrID { get; set; }
        public string ShopLbrDesc { get; set; }
        public string ShopLbrUom { get; set; }
        public decimal ShopLbrMhs { get; set; }
        public int ShopLocID { get; set; }
        public string Sort { get; set; }
    
        public virtual ICollection<BOM03_LaborRoutings> BOM03_LaborRoutings { get; set; }
        public virtual Setup31_ShopLocations Setup31_ShopLocations { get; set; }
    }
}
