//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup97_ZipCodes
    {
        public string Zipcode { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }
    }
}
