//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBIDMhsOnsiteDetail
    {
        public int BIDID { get; set; }
        public int FieldLbrDtlsID { get; set; }
        public Nullable<decimal> MhsEa { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> MhsOnsite { get; set; }
        public decimal LaborDiscount { get; set; }
        public Nullable<decimal> MhsOnsiteBid { get; set; }
        public Nullable<decimal> MhsOnSiteBidTot { get; set; }
        public decimal LbrHoldBack { get; set; }
        public Nullable<decimal> MhsOnsitePaid { get; set; }
        public Nullable<decimal> MhsOnsitePaidTot { get; set; }
    }
}
