//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBOMUpdateInventoryCostsAndWt
    {
        public string PartNum { get; set; }
        public Nullable<decimal> BomCost { get; set; }
        public Nullable<decimal> BomMhs { get; set; }
        public Nullable<decimal> BomWeight { get; set; }
        public string ProcurementTypeID { get; set; }
    }
}
