//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCrewCostSummary
    {
        public string MhRateID { get; set; }
        public Nullable<int> CrewHeadCount { get; set; }
        public Nullable<decimal> CrewOnsiteMhs { get; set; }
        public Nullable<decimal> CrewAvgOnsiteRate { get; set; }
        public Nullable<decimal> CrewOnsiteDollars { get; set; }
        public Nullable<decimal> CrewDriveMhs { get; set; }
        public Nullable<decimal> CrewAvgOffsiteRate { get; set; }
        public Nullable<decimal> CrewDriveDollars { get; set; }
        public Nullable<decimal> CrewLoadMhs { get; set; }
        public Nullable<decimal> CrewLoadDollars { get; set; }
        public Nullable<decimal> CrewTotalMhs { get; set; }
        public Nullable<decimal> CrewTotalDollars { get; set; }
        public Nullable<decimal> CrewIndirectRate { get; set; }
        public Nullable<decimal> CrewTotalIndirects { get; set; }
        public Nullable<decimal> CrewLoadTimePercent { get; set; }
        public Nullable<decimal> CrewDriveTimePercent { get; set; }
        public Nullable<decimal> CrewOnsiteTimePercent { get; set; }
    }
}
