//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGeoDrawPricing
    {
        public string StylePricingNumber { get; set; }
        public string StyleName { get; set; }
        public int Heigth { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> GeoDrawMatPricingCost { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL1 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL2 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL3 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL4 { get; set; }
        public Nullable<decimal> GeoDrawMatPricingL5 { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
        public string FenceType { get; set; }
        public int PFPComponentTypeId { get; set; }
        public int DisplayOrder { get; set; }
        public decimal Sort { get; set; }
    }
}
