//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPFPLaborCost
    {
        public int PFPId { get; set; }
        public Nullable<decimal> OnsiteMhsBid { get; set; }
        public Nullable<decimal> LoadMhsBid { get; set; }
        public Nullable<decimal> DriveMhsBid { get; set; }
        public Nullable<decimal> TotalMhsBid { get; set; }
        public Nullable<decimal> OnsiteDollarsPaid { get; set; }
        public Nullable<decimal> LoadDollarsPaid { get; set; }
        public Nullable<decimal> DriveDollarsPaid { get; set; }
        public Nullable<decimal> TotalDollarsPaid { get; set; }
        public Nullable<decimal> BenefitRate { get; set; }
        public Nullable<decimal> BenefitDollars { get; set; }
        public Nullable<decimal> RetirementBenefitRate { get; set; }
        public Nullable<decimal> RetirementDollars { get; set; }
        public Nullable<decimal> PayrollTaxRate { get; set; }
        public Nullable<decimal> PayrollTax { get; set; }
        public Nullable<decimal> WorkCompRate { get; set; }
        public Nullable<decimal> WorkComp { get; set; }
    }
}
