//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MAS_Imp_LvlPricing
    {
        public int BreakQty1 { get; set; }
        public int BreakQty2 { get; set; }
        public int BreakQty3 { get; set; }
        public int BreakQty4 { get; set; }
        public Nullable<decimal> DiscountMarkupPriceRate1 { get; set; }
        public Nullable<decimal> DiscountMarkupPriceRate2 { get; set; }
        public Nullable<decimal> DiscountMarkupPriceRate3 { get; set; }
        public Nullable<decimal> DiscountMarkupPriceRate4 { get; set; }
        public string PartNum { get; set; }
        public string ItemMethod { get; set; }
        public Nullable<decimal> DiscountMarkupPriceRate5 { get; set; }
    }
}
