//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MAS_Imp_InvPricing
    {
        public string Item_Number { get; set; }
        public Nullable<decimal> Standard_Price { get; set; }
        public decimal Standard_Cost { get; set; }
        public int RetailPrice { get; set; }
    }
}
